// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: LithumeBms

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_Header;
lv_obj_t *ui_DateLabel;
lv_obj_t *ui_TimeLabel;
lv_obj_t *ui_HeaderTitle;
lv_obj_t *ui_MainLeftPannel;
lv_obj_t *ui_TotalVoltage10;
lv_obj_t *ui_lblOutputVoltage;
lv_obj_t *ui_lblTotalAmpere;
lv_obj_t *ui_lblTotalTemperature;
lv_obj_t *ui_TotalVoltageLabel;
lv_obj_t *ui_lblHighVoltage;
lv_obj_t *ui_lblLowVoltage;
lv_obj_t *ui_lblDiff;
lv_obj_t *ui_HighImpedance;
lv_obj_t *ui_LowImpedance;
lv_obj_t *ui_AverageImpendance;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_MainMidPannel;
lv_obj_t *ui_CellInfo1;
lv_obj_t *ui_CellNo1;
lv_obj_t *ui_lblvoltage1;
lv_obj_t *ui_CellInfo2;
lv_obj_t *ui_CellNo2;
lv_obj_t *ui_lblvoltage2;
lv_obj_t *ui_CellInfo3;
lv_obj_t *ui_CellNo3;
lv_obj_t *ui_lblvoltage3;
lv_obj_t *ui_CellInfo4;
lv_obj_t *ui_CellNo4;
lv_obj_t *ui_lblvoltage4;
lv_obj_t *ui_CellInfo5;
lv_obj_t *ui_CellNo5;
lv_obj_t *ui_lblvoltage5;
lv_obj_t *ui_CellInfo6;
lv_obj_t *ui_CellNo6;
lv_obj_t *ui_lblvoltage6;
lv_obj_t *ui_CellInfo7;
lv_obj_t *ui_CellNo7;
lv_obj_t *ui_lblvoltage7;
lv_obj_t *ui_CellInfo8;
lv_obj_t *ui_CellNo8;
lv_obj_t *ui_lblvoltage8;
lv_obj_t *ui_CellInfo9;
lv_obj_t *ui_CellNo9;
lv_obj_t *ui_lblvoltage9;
lv_obj_t *ui_CellInfo10;
lv_obj_t *ui_CellNo10;
lv_obj_t *ui_lblvoltage10;
lv_obj_t *ui_CellInfo11;
lv_obj_t *ui_CellNo11;
lv_obj_t *ui_lblvoltage11;
lv_obj_t *ui_CellInfo12;
lv_obj_t *ui_CellNo12;
lv_obj_t *ui_lblvoltage12;
lv_obj_t *ui_CellInfo13;
lv_obj_t *ui_CellNo13;
lv_obj_t *ui_lblvoltage13;
lv_obj_t *ui_CellInfo14;
lv_obj_t *ui_CellNo14;
lv_obj_t *ui_lblvoltage14;
lv_obj_t *ui_CellInfo15;
lv_obj_t *ui_CellNo15;
lv_obj_t *ui_lblvoltage15;
lv_obj_t *ui_MainBottomPannel;
lv_obj_t *ui_CompanyLabel;
lv_obj_t *ui_CompanyLabel1;
lv_obj_t *ui_VersionLabel;
lv_obj_t *ui_MainRightPanel;
void ui_event_btnPack1( lv_event_t * e);
lv_obj_t *ui_btnPack1;
lv_obj_t *ui_lblPack1;
void ui_event_btnPack2( lv_event_t * e);
lv_obj_t *ui_btnPack2;
lv_obj_t *ui_lblPack2;
void ui_event_btnPack3( lv_event_t * e);
lv_obj_t *ui_btnPack3;
lv_obj_t *ui_lblPack3;
void ui_event_btnPack4( lv_event_t * e);
lv_obj_t *ui_btnPack4;
lv_obj_t *ui_lblPack4;
void ui_event_btnPack5( lv_event_t * e);
lv_obj_t *ui_btnPack5;
lv_obj_t *ui_lblPack5;
void ui_event_btnPack6( lv_event_t * e);
lv_obj_t *ui_btnPack6;
lv_obj_t *ui_lblPack6;
void ui_event_btnPack7( lv_event_t * e);
lv_obj_t *ui_btnPack7;
lv_obj_t *ui_lblPack7;
void ui_event_btnPack8( lv_event_t * e);
lv_obj_t *ui_btnPack8;
lv_obj_t *ui_lblPack8;


// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
lv_obj_t *ui_SettingScreen;
lv_obj_t *ui_SetHeader;
lv_obj_t *ui_DateLabel1;
lv_obj_t *ui_TimeLabel1;
lv_obj_t *ui_HeaderTitle1;
lv_obj_t *ui_SetLeftPannel;
lv_obj_t *ui_TotalVoltage1;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label2;
void ui_event_SaveSettingButton( lv_event_t * e);
lv_obj_t *ui_SaveSettingButton;
lv_obj_t *ui_Label8;
lv_obj_t *ui_SetRightPannel;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_lblIPADDRESS;
void ui_event_txtIPADDRESS1( lv_event_t * e);
lv_obj_t *ui_txtIPADDRESS1;
void ui_event_txtIPADDRESS2( lv_event_t * e);
lv_obj_t *ui_txtIPADDRESS2;
void ui_event_txtIPADDRESS3( lv_event_t * e);
lv_obj_t *ui_txtIPADDRESS3;
void ui_event_txtIPADDRESS4( lv_event_t * e);
lv_obj_t *ui_txtIPADDRESS4;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_lblIPADDRESS1;
void ui_event_txtSUBNET1( lv_event_t * e);
lv_obj_t *ui_txtSUBNET1;
void ui_event_txtSUBNET2( lv_event_t * e);
lv_obj_t *ui_txtSUBNET2;
void ui_event_txtSUBNET3( lv_event_t * e);
lv_obj_t *ui_txtSUBNET3;
void ui_event_txtSUBNET4( lv_event_t * e);
lv_obj_t *ui_txtSUBNET4;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_lblIPADDRESS2;
void ui_event_txtGATEWAY1( lv_event_t * e);
lv_obj_t *ui_txtGATEWAY1;
void ui_event_txtGATEWAY2( lv_event_t * e);
lv_obj_t *ui_txtGATEWAY2;
void ui_event_txtGATEWAY3( lv_event_t * e);
lv_obj_t *ui_txtGATEWAY3;
void ui_event_txtGATEWAY4( lv_event_t * e);
lv_obj_t *ui_txtGATEWAY4;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_lblIPADDRESS3;
void ui_event_txtDEVICENAME( lv_event_t * e);
lv_obj_t *ui_txtDEVICENAME;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_lblTime;
lv_obj_t *ui_txtYear;
lv_obj_t *ui_txtMonth;
lv_obj_t *ui_txtDay;
lv_obj_t *ui_txtTime;
lv_obj_t *ui_txtMinute;
lv_obj_t *ui_txtSecond;
lv_obj_t *ui_SetBottomPannel;
lv_obj_t *ui_CompanyLabel2;
lv_obj_t *ui_CompanyLabel3;
lv_obj_t *ui_VersionLabel1;
lv_obj_t *ui_Keyboard1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

#include <Arduino.h>
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_SettingScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT/*LV_SCR_LOAD_ANIM_FADE_ON */, 1, 10, &ui_SettingScreen_screen_init);
}
}
void ui_event_btnPack1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btnPackChange( e );
      btnEventPack1( e );
}
}
void ui_event_btnPack2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btnEventPack2( e );
}
}
void ui_event_btnPack3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btnPackChange( e );
      btnEventPack3( e );
}
}
void ui_event_btnPack4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btnPackChange( e );
      btnEventPack4( e );
}
}
void ui_event_btnPack5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btnPackChange( e );
      btnEventPack5( e );
}
}
void ui_event_btnPack6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btnPackChange( e );
      btnEventPack6( e );
}
}
void ui_event_btnPack7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btnPackChange( e );
      btnEventPack7( e );
}
}
void ui_event_btnPack8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btnPackChange( e );
      btnEventPack8( e );
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 10, &ui_MainScreen_screen_init);
}
}
void ui_event_SaveSettingButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      saveButtenEvent( e );
}
}
void ui_event_txtIPADDRESS1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    lv_obj_clear_flag(ui_Keyboard1,LV_OBJ_FLAG_HIDDEN);
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtIPADDRESS1);
}
}
void ui_event_txtIPADDRESS2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtIPADDRESS2);
}
}
void ui_event_txtIPADDRESS3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtIPADDRESS3);
}
}
void ui_event_txtIPADDRESS4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtIPADDRESS4);
}
}
void ui_event_txtSUBNET1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtSUBNET1);
}
}
void ui_event_txtSUBNET2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtSUBNET2);
}
}
void ui_event_txtSUBNET3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtSUBNET3);
}
}
void ui_event_txtSUBNET4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtSUBNET4);
}
}
void ui_event_txtGATEWAY1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtGATEWAY1);
}
}
void ui_event_txtGATEWAY2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtGATEWAY2);
}
}
void ui_event_txtGATEWAY3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtGATEWAY3);
}
}
void ui_event_txtGATEWAY4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtGATEWAY4);
}
}
void ui_event_txtDEVICENAME( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_txtDEVICENAME);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui_SettingScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
