// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: LithumeBms

#ifndef _LITHUMEBMS_UI_H
#define _LITHUMEBMS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui_DateLabel;
extern lv_obj_t *ui_TimeLabel;
extern lv_obj_t *ui_HeaderTitle;
extern lv_obj_t *ui_MainLeftPannel;
extern lv_obj_t *ui_TotalVoltage10;
extern lv_obj_t *ui_lblOutputVoltage;
extern lv_obj_t *ui_lblTotalAmpere;
extern lv_obj_t *ui_lblTotalTemperature;
extern lv_obj_t *ui_TotalVoltageLabel;
extern lv_obj_t *ui_lblHighVoltage;
extern lv_obj_t *ui_lblLowVoltage;
extern lv_obj_t *ui_lblDiff;
extern lv_obj_t *ui_HighImpedance;
extern lv_obj_t *ui_LowImpedance;
extern lv_obj_t *ui_AverageImpendance;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_MainMidPannel;
extern lv_obj_t *ui_CellInfo1;
extern lv_obj_t *ui_CellNo1;
extern lv_obj_t *ui_lblvoltage1;
extern lv_obj_t *ui_CellInfo2;
extern lv_obj_t *ui_CellNo2;
extern lv_obj_t *ui_lblvoltage2;
extern lv_obj_t *ui_CellInfo3;
extern lv_obj_t *ui_CellNo3;
extern lv_obj_t *ui_lblvoltage3;
extern lv_obj_t *ui_CellInfo4;
extern lv_obj_t *ui_CellNo4;
extern lv_obj_t *ui_lblvoltage4;
extern lv_obj_t *ui_CellInfo5;
extern lv_obj_t *ui_CellNo5;
extern lv_obj_t *ui_lblvoltage5;
extern lv_obj_t *ui_CellInfo6;
extern lv_obj_t *ui_CellNo6;
extern lv_obj_t *ui_lblvoltage6;
extern lv_obj_t *ui_CellInfo7;
extern lv_obj_t *ui_CellNo7;
extern lv_obj_t *ui_lblvoltage7;
extern lv_obj_t *ui_CellInfo8;
extern lv_obj_t *ui_CellNo8;
extern lv_obj_t *ui_lblvoltage8;
extern lv_obj_t *ui_CellInfo9;
extern lv_obj_t *ui_CellNo9;
extern lv_obj_t *ui_lblvoltage9;
extern lv_obj_t *ui_CellInfo10;
extern lv_obj_t *ui_CellNo10;
extern lv_obj_t *ui_lblvoltage10;
extern lv_obj_t *ui_CellInfo11;
extern lv_obj_t *ui_CellNo11;
extern lv_obj_t *ui_lblvoltage11;
extern lv_obj_t *ui_CellInfo12;
extern lv_obj_t *ui_CellNo12;
extern lv_obj_t *ui_lblvoltage12;
extern lv_obj_t *ui_CellInfo13;
extern lv_obj_t *ui_CellNo13;
extern lv_obj_t *ui_lblvoltage13;
extern lv_obj_t *ui_CellInfo14;
extern lv_obj_t *ui_CellNo14;
extern lv_obj_t *ui_lblvoltage14;
extern lv_obj_t *ui_CellInfo15;
extern lv_obj_t *ui_CellNo15;
extern lv_obj_t *ui_lblvoltage15;
extern lv_obj_t *ui_MainBottomPannel;
extern lv_obj_t *ui_CompanyLabel;
extern lv_obj_t *ui_CompanyLabel1;
extern lv_obj_t *ui_VersionLabel;
extern lv_obj_t *ui_MainRightPanel;
void ui_event_btnPack1( lv_event_t * e);
extern lv_obj_t *ui_btnPack1;
extern lv_obj_t *ui_lblPack1;
void ui_event_btnPack2( lv_event_t * e);
extern lv_obj_t *ui_btnPack2;
extern lv_obj_t *ui_lblPack2;
void ui_event_btnPack3( lv_event_t * e);
extern lv_obj_t *ui_btnPack3;
extern lv_obj_t *ui_lblPack3;
void ui_event_btnPack4( lv_event_t * e);
extern lv_obj_t *ui_btnPack4;
extern lv_obj_t *ui_lblPack4;
void ui_event_btnPack5( lv_event_t * e);
extern lv_obj_t *ui_btnPack5;
extern lv_obj_t *ui_lblPack5;
void ui_event_btnPack6( lv_event_t * e);
extern lv_obj_t *ui_btnPack6;
extern lv_obj_t *ui_lblPack6;
void ui_event_btnPack7( lv_event_t * e);
extern lv_obj_t *ui_btnPack7;
extern lv_obj_t *ui_lblPack7;
void ui_event_btnPack8( lv_event_t * e);
extern lv_obj_t *ui_btnPack8;
extern lv_obj_t *ui_lblPack8;
// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
extern lv_obj_t *ui_SettingScreen;
extern lv_obj_t *ui_SetHeader;
extern lv_obj_t *ui_DateLabel1;
extern lv_obj_t *ui_TimeLabel1;
extern lv_obj_t *ui_HeaderTitle1;
extern lv_obj_t *ui_SetLeftPannel;
extern lv_obj_t *ui_TotalVoltage1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label2;
void ui_event_SaveSettingButton( lv_event_t * e);
extern lv_obj_t *ui_SaveSettingButton;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_SetRightPannel;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_lblIPADDRESS;
void ui_event_txtIPADDRESS1( lv_event_t * e);
extern lv_obj_t *ui_txtIPADDRESS1;
void ui_event_txtIPADDRESS2( lv_event_t * e);
extern lv_obj_t *ui_txtIPADDRESS2;
void ui_event_txtIPADDRESS3( lv_event_t * e);
extern lv_obj_t *ui_txtIPADDRESS3;
void ui_event_txtIPADDRESS4( lv_event_t * e);
extern lv_obj_t *ui_txtIPADDRESS4;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_lblIPADDRESS1;
void ui_event_txtSUBNET1( lv_event_t * e);
extern lv_obj_t *ui_txtSUBNET1;
void ui_event_txtSUBNET2( lv_event_t * e);
extern lv_obj_t *ui_txtSUBNET2;
void ui_event_txtSUBNET3( lv_event_t * e);
extern lv_obj_t *ui_txtSUBNET3;
void ui_event_txtSUBNET4( lv_event_t * e);
extern lv_obj_t *ui_txtSUBNET4;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_lblIPADDRESS2;
void ui_event_txtGATEWAY1( lv_event_t * e);
extern lv_obj_t *ui_txtGATEWAY1;
void ui_event_txtGATEWAY2( lv_event_t * e);
extern lv_obj_t *ui_txtGATEWAY2;
void ui_event_txtGATEWAY3( lv_event_t * e);
extern lv_obj_t *ui_txtGATEWAY3;
void ui_event_txtGATEWAY4( lv_event_t * e);
extern lv_obj_t *ui_txtGATEWAY4;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_lblIPADDRESS3;
void ui_event_txtDEVICENAME( lv_event_t * e);
extern lv_obj_t *ui_txtDEVICENAME;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_lblTime;
extern lv_obj_t *ui_txtYear;
extern lv_obj_t *ui_txtMonth;
extern lv_obj_t *ui_txtDay;
extern lv_obj_t *ui_txtTime;
extern lv_obj_t *ui_txtMinute;
extern lv_obj_t *ui_txtSecond;
extern lv_obj_t *ui_SetBottomPannel;
extern lv_obj_t *ui_CompanyLabel2;
extern lv_obj_t *ui_CompanyLabel3;
extern lv_obj_t *ui_VersionLabel1;
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_Arial);
LV_FONT_DECLARE( ui_font_arial14);
LV_FONT_DECLARE( ui_font_arial16);
LV_FONT_DECLARE( ui_font_arial26);
LV_FONT_DECLARE( ui_font_arial28);
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_Greek);
LV_FONT_DECLARE( ui_font_malgunFont1);
LV_FONT_DECLARE( ui_font_montserrat16);
LV_FONT_DECLARE( ui_font_montserrat26);
LV_FONT_DECLARE( ui_font_montserrat28);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
