// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: LithumeBms

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x4C4B55), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Header, 800);
lv_obj_set_height( ui_Header, 48);
lv_obj_set_align( ui_Header, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Header, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0x2F2C2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Header, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Header, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateLabel = lv_label_create(ui_Header);
lv_obj_set_width( ui_DateLabel, 120);
lv_obj_set_height( ui_DateLabel, 15);
lv_obj_set_align( ui_DateLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_DateLabel,"2023-11-03");
lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DateLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeLabel = lv_label_create(ui_Header);
lv_obj_set_width( ui_TimeLabel, 120);
lv_obj_set_height( ui_TimeLabel, 15);
lv_obj_set_align( ui_TimeLabel, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_TimeLabel,"PM 8:35");
lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaderTitle = lv_label_create(ui_Header);
lv_obj_set_width( ui_HeaderTitle, 400);
lv_obj_set_height( ui_HeaderTitle, 30);
lv_obj_set_align( ui_HeaderTitle, LV_ALIGN_CENTER );
lv_label_set_text(ui_HeaderTitle,"LITHUME BAT #1");
lv_obj_set_style_text_color(ui_HeaderTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeaderTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_HeaderTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeaderTitle, &ui_font_arial28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainLeftPannel = lv_obj_create(ui_MainScreen);
lv_obj_set_height( ui_MainLeftPannel, 384);
lv_obj_set_width( ui_MainLeftPannel, lv_pct(20));
lv_obj_set_align( ui_MainLeftPannel, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_MainLeftPannel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_MainLeftPannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_MainLeftPannel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MainLeftPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainLeftPannel, lv_color_hex(0x353030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainLeftPannel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainLeftPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TotalVoltage10 = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_TotalVoltage10, 120);
lv_obj_set_height( ui_TotalVoltage10, 15);
lv_obj_set_x( ui_TotalVoltage10, 2 );
lv_obj_set_y( ui_TotalVoltage10, 9 );
lv_label_set_text(ui_TotalVoltage10,"SYSTEM INFO");
lv_obj_set_style_text_color(ui_TotalVoltage10, lv_color_hex(0x1401F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TotalVoltage10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblOutputVoltage = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_lblOutputVoltage, 120);
lv_obj_set_height( ui_lblOutputVoltage, 15);
lv_label_set_text(ui_lblOutputVoltage,"AVG    : 52.5V");
lv_obj_set_style_text_color(ui_lblOutputVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblOutputVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTotalAmpere = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_lblTotalAmpere, 120);
lv_obj_set_height( ui_lblTotalAmpere, 15);
lv_label_set_text(ui_lblTotalAmpere,"AMP    : 33A");
lv_obj_set_style_text_color(ui_lblTotalAmpere, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTotalAmpere, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTotalTemperature = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_lblTotalTemperature, 120);
lv_obj_set_height( ui_lblTotalTemperature, 15);
lv_label_set_text(ui_lblTotalTemperature,"TEMP  : 25C");
lv_obj_set_style_text_color(ui_lblTotalTemperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTotalTemperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TotalVoltageLabel = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_TotalVoltageLabel, 120);
lv_obj_set_height( ui_TotalVoltageLabel, 15);
lv_label_set_text(ui_TotalVoltageLabel,"CELL INFO");
lv_obj_set_style_text_color(ui_TotalVoltageLabel, lv_color_hex(0x1401F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TotalVoltageLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblHighVoltage = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_lblHighVoltage, 120);
lv_obj_set_height( ui_lblHighVoltage, 15);
lv_label_set_text(ui_lblHighVoltage,"HVOL : 3.34V");
lv_obj_set_style_text_color(ui_lblHighVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblHighVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblLowVoltage = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_lblLowVoltage, 120);
lv_obj_set_height( ui_lblLowVoltage, 15);
lv_label_set_text(ui_lblLowVoltage,"LVOL : 3.31V");
lv_obj_set_style_text_color(ui_lblLowVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblLowVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDiff = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_lblDiff, 120);
lv_obj_set_height( ui_lblDiff, 15);
lv_label_set_text(ui_lblDiff,"DIFF  : 20mV");
lv_obj_set_style_text_color(ui_lblDiff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblDiff, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HighImpedance = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_HighImpedance, 120);
lv_obj_set_height( ui_HighImpedance, LV_SIZE_CONTENT);   /// 15
lv_label_set_text(ui_HighImpedance,"");
lv_obj_set_style_text_color(ui_HighImpedance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HighImpedance, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LowImpedance = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_LowImpedance, 120);
lv_obj_set_height( ui_LowImpedance, 15);
lv_obj_set_x( ui_LowImpedance, 1 );
lv_obj_set_y( ui_LowImpedance, 0 );
lv_label_set_text(ui_LowImpedance,"");
lv_obj_set_style_text_color(ui_LowImpedance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LowImpedance, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AverageImpendance = lv_label_create(ui_MainLeftPannel);
lv_obj_set_width( ui_AverageImpendance, 120);
lv_obj_set_height( ui_AverageImpendance, 15);
lv_obj_set_x( ui_AverageImpendance, 1 );
lv_obj_set_y( ui_AverageImpendance, 0 );
lv_label_set_text(ui_AverageImpendance,"");
lv_obj_set_style_text_color(ui_AverageImpendance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AverageImpendance, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_MainLeftPannel);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 30);
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label1, 50);
lv_obj_set_height( ui_Label1, 15);
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"설 정");
lv_obj_set_style_text_font(ui_Label1, &ui_font_malgunFont1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainMidPannel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_MainMidPannel, lv_pct(55));
lv_obj_set_height( ui_MainMidPannel, lv_pct(75));
lv_obj_set_x( ui_MainMidPannel, -181 );
lv_obj_set_y( ui_MainMidPannel, -1 );
lv_obj_set_align( ui_MainMidPannel, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_MainMidPannel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_MainMidPannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_MainMidPannel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainMidPannel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainMidPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainMidPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MainMidPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MainMidPannel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MainMidPannel, 35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MainMidPannel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MainMidPannel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MainMidPannel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo1 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo1, lv_pct(18));
lv_obj_set_height( ui_CellInfo1, lv_pct(23));
lv_obj_set_align( ui_CellInfo1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo1 = lv_label_create(ui_CellInfo1);
lv_obj_set_width( ui_CellNo1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo1, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo1,"1");
lv_obj_set_style_text_color(ui_CellNo1, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage1 = lv_label_create(ui_CellInfo1);
lv_obj_set_width( ui_lblvoltage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage1, 15 );
lv_obj_set_y( ui_lblvoltage1, 15 );
lv_label_set_text(ui_lblvoltage1,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo2 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo2, lv_pct(18));
lv_obj_set_height( ui_CellInfo2, lv_pct(23));
lv_obj_set_align( ui_CellInfo2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo2, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo2 = lv_label_create(ui_CellInfo2);
lv_obj_set_width( ui_CellNo2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo2, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo2,"2");
lv_obj_set_style_text_color(ui_CellNo2, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage2 = lv_label_create(ui_CellInfo2);
lv_obj_set_width( ui_lblvoltage2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage2, 15 );
lv_obj_set_y( ui_lblvoltage2, 15 );
lv_label_set_text(ui_lblvoltage2,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo3 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo3, lv_pct(18));
lv_obj_set_height( ui_CellInfo3, lv_pct(23));
lv_obj_set_align( ui_CellInfo3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo3, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo3 = lv_label_create(ui_CellInfo3);
lv_obj_set_width( ui_CellNo3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo3, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo3,"3");
lv_obj_set_style_text_color(ui_CellNo3, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage3 = lv_label_create(ui_CellInfo3);
lv_obj_set_width( ui_lblvoltage3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage3, 15 );
lv_obj_set_y( ui_lblvoltage3, 15 );
lv_label_set_text(ui_lblvoltage3,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo4 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo4, lv_pct(18));
lv_obj_set_height( ui_CellInfo4, lv_pct(23));
lv_obj_set_align( ui_CellInfo4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo4, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo4 = lv_label_create(ui_CellInfo4);
lv_obj_set_width( ui_CellNo4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo4, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo4,"4");
lv_obj_set_style_text_color(ui_CellNo4, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage4 = lv_label_create(ui_CellInfo4);
lv_obj_set_width( ui_lblvoltage4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage4, 15 );
lv_obj_set_y( ui_lblvoltage4, 15 );
lv_label_set_text(ui_lblvoltage4,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo5 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo5, lv_pct(18));
lv_obj_set_height( ui_CellInfo5, lv_pct(23));
lv_obj_set_align( ui_CellInfo5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo5, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo5 = lv_label_create(ui_CellInfo5);
lv_obj_set_width( ui_CellNo5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo5, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo5,"5");
lv_obj_set_style_text_color(ui_CellNo5, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo5, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage5 = lv_label_create(ui_CellInfo5);
lv_obj_set_width( ui_lblvoltage5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage5, 15 );
lv_obj_set_y( ui_lblvoltage5, 15 );
lv_label_set_text(ui_lblvoltage5,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage5, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo6 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo6, lv_pct(18));
lv_obj_set_height( ui_CellInfo6, lv_pct(23));
lv_obj_set_align( ui_CellInfo6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo6, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo6, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo6 = lv_label_create(ui_CellInfo6);
lv_obj_set_width( ui_CellNo6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo6, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo6,"6");
lv_obj_set_style_text_color(ui_CellNo6, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo6, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage6 = lv_label_create(ui_CellInfo6);
lv_obj_set_width( ui_lblvoltage6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage6, 15 );
lv_obj_set_y( ui_lblvoltage6, 15 );
lv_label_set_text(ui_lblvoltage6,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage6, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo7 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo7, lv_pct(18));
lv_obj_set_height( ui_CellInfo7, lv_pct(23));
lv_obj_set_align( ui_CellInfo7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo7, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo7 = lv_label_create(ui_CellInfo7);
lv_obj_set_width( ui_CellNo7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo7, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo7,"7");
lv_obj_set_style_text_color(ui_CellNo7, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo7, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage7 = lv_label_create(ui_CellInfo7);
lv_obj_set_width( ui_lblvoltage7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage7, 15 );
lv_obj_set_y( ui_lblvoltage7, 15 );
lv_label_set_text(ui_lblvoltage7,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage7, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo8 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo8, lv_pct(18));
lv_obj_set_height( ui_CellInfo8, lv_pct(23));
lv_obj_set_align( ui_CellInfo8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo8, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo8 = lv_label_create(ui_CellInfo8);
lv_obj_set_width( ui_CellNo8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo8, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo8,"8");
lv_obj_set_style_text_color(ui_CellNo8, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo8, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage8 = lv_label_create(ui_CellInfo8);
lv_obj_set_width( ui_lblvoltage8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage8, 15 );
lv_obj_set_y( ui_lblvoltage8, 15 );
lv_label_set_text(ui_lblvoltage8,"12.3V\n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage8, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo9 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo9, lv_pct(18));
lv_obj_set_height( ui_CellInfo9, lv_pct(23));
lv_obj_set_align( ui_CellInfo9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo9, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo9, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo9, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo9, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo9, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo9, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo9 = lv_label_create(ui_CellInfo9);
lv_obj_set_width( ui_CellNo9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo9, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo9,"8");
lv_obj_set_style_text_color(ui_CellNo9, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo9, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage9 = lv_label_create(ui_CellInfo9);
lv_obj_set_width( ui_lblvoltage9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage9, 15 );
lv_obj_set_y( ui_lblvoltage9, 15 );
lv_label_set_text(ui_lblvoltage9,"12.3V\n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage9, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo10 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo10, lv_pct(18));
lv_obj_set_height( ui_CellInfo10, lv_pct(23));
lv_obj_set_align( ui_CellInfo10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo10, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo10 = lv_label_create(ui_CellInfo10);
lv_obj_set_width( ui_CellNo10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo10, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo10,"10");
lv_obj_set_style_text_color(ui_CellNo10, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo10, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage10 = lv_label_create(ui_CellInfo10);
lv_obj_set_width( ui_lblvoltage10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage10, 15 );
lv_obj_set_y( ui_lblvoltage10, 15 );
lv_label_set_text(ui_lblvoltage10,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage10, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo11 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo11, lv_pct(18));
lv_obj_set_height( ui_CellInfo11, lv_pct(23));
lv_obj_set_align( ui_CellInfo11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo11, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo11 = lv_label_create(ui_CellInfo11);
lv_obj_set_width( ui_CellNo11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo11, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo11,"11");
lv_obj_set_style_text_color(ui_CellNo11, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo11, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage11 = lv_label_create(ui_CellInfo11);
lv_obj_set_width( ui_lblvoltage11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage11, 15 );
lv_obj_set_y( ui_lblvoltage11, 15 );
lv_label_set_text(ui_lblvoltage11,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage11, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo12 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo12, lv_pct(18));
lv_obj_set_height( ui_CellInfo12, lv_pct(23));
lv_obj_set_align( ui_CellInfo12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo12, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo12, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo12, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo12, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo12, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo12, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo12 = lv_label_create(ui_CellInfo12);
lv_obj_set_width( ui_CellNo12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo12, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo12,"12");
lv_obj_set_style_text_color(ui_CellNo12, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo12, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage12 = lv_label_create(ui_CellInfo12);
lv_obj_set_width( ui_lblvoltage12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage12, 15 );
lv_obj_set_y( ui_lblvoltage12, 15 );
lv_label_set_text(ui_lblvoltage12,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage12, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo13 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo13, lv_pct(18));
lv_obj_set_height( ui_CellInfo13, lv_pct(23));
lv_obj_set_align( ui_CellInfo13, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo13, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo13, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo13, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo13, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo13, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo13, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo13, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo13, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo13, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo13, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo13 = lv_label_create(ui_CellInfo13);
lv_obj_set_width( ui_CellNo13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo13, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo13,"13");
lv_obj_set_style_text_color(ui_CellNo13, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo13, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage13 = lv_label_create(ui_CellInfo13);
lv_obj_set_width( ui_lblvoltage13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage13, 15 );
lv_obj_set_y( ui_lblvoltage13, 15 );
lv_label_set_text(ui_lblvoltage13,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage13, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo14 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo14, lv_pct(18));
lv_obj_set_height( ui_CellInfo14, lv_pct(23));
lv_obj_set_align( ui_CellInfo14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo14, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo14, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo14, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo14, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo14, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo14, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo14, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo14, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo14, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo14, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo14 = lv_label_create(ui_CellInfo14);
lv_obj_set_width( ui_CellNo14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo14, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo14,"14");
lv_obj_set_style_text_color(ui_CellNo14, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo14, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage14 = lv_label_create(ui_CellInfo14);
lv_obj_set_width( ui_lblvoltage14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage14, 15 );
lv_obj_set_y( ui_lblvoltage14, 15 );
lv_label_set_text(ui_lblvoltage14,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage14, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CellInfo15 = lv_obj_create(ui_MainMidPannel);
lv_obj_set_width( ui_CellInfo15, lv_pct(18));
lv_obj_set_height( ui_CellInfo15, lv_pct(23));
lv_obj_set_align( ui_CellInfo15, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CellInfo15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CellInfo15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CellInfo15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellInfo15, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo15, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo15, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo15, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_CellInfo15, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellInfo15, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellInfo15, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellInfo15, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellInfo15, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellInfo15, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_CellNo15 = lv_label_create(ui_CellInfo15);
lv_obj_set_width( ui_CellNo15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CellNo15, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_CellNo15,"15");
lv_obj_set_style_text_color(ui_CellNo15, lv_color_hex(0x05FC00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CellNo15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_CellNo15, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_CellNo15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CellNo15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CellNo15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CellNo15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_CellNo15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_CellNo15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblvoltage15 = lv_label_create(ui_CellInfo15);
lv_obj_set_width( ui_lblvoltage15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblvoltage15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblvoltage15, 15 );
lv_obj_set_y( ui_lblvoltage15, 15 );
lv_label_set_text(ui_lblvoltage15,"12.3V \n(23C)");
lv_obj_set_style_text_color(ui_lblvoltage15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblvoltage15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_lblvoltage15, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblvoltage15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblvoltage15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblvoltage15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblvoltage15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_lblvoltage15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_lblvoltage15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainBottomPannel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_MainBottomPannel, 800);
lv_obj_set_height( ui_MainBottomPannel, 48);
lv_obj_set_align( ui_MainBottomPannel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_MainBottomPannel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_MainBottomPannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_MainBottomPannel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MainBottomPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MainBottomPannel, lv_color_hex(0x2F2C2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainBottomPannel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MainBottomPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CompanyLabel = lv_label_create(ui_MainBottomPannel);
lv_obj_set_width( ui_CompanyLabel, 120);
lv_obj_set_height( ui_CompanyLabel, 15);
lv_obj_set_align( ui_CompanyLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_CompanyLabel,"IFTECH Co.,LTD");
lv_obj_set_style_text_color(ui_CompanyLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CompanyLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CompanyLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CompanyLabel1 = lv_label_create(ui_MainBottomPannel);
lv_obj_set_width( ui_CompanyLabel1, 560);
lv_obj_set_height( ui_CompanyLabel1, 15);
lv_obj_set_align( ui_CompanyLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_CompanyLabel1,"STATUS : NORMAL");
lv_obj_set_style_text_color(ui_CompanyLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CompanyLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CompanyLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VersionLabel = lv_label_create(ui_MainBottomPannel);
lv_obj_set_width( ui_VersionLabel, 120);
lv_obj_set_height( ui_VersionLabel, 15);
lv_obj_set_align( ui_VersionLabel, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_VersionLabel,"V1.0.1");
lv_obj_set_style_text_color(ui_VersionLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_VersionLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_VersionLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainRightPanel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_MainRightPanel, lv_pct(20));
lv_obj_set_height( ui_MainRightPanel, lv_pct(80));
lv_obj_set_x( ui_MainRightPanel, 0 );
lv_obj_set_y( ui_MainRightPanel, 1 );
lv_obj_set_align( ui_MainRightPanel, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_MainRightPanel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_MainRightPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_MainRightPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainRightPanel, lv_color_hex(0x353030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainRightPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MainRightPanel, lv_color_hex(0x7F6C6C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MainRightPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MainRightPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MainRightPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MainRightPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MainRightPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPack1 = lv_btn_create(ui_MainRightPanel);
lv_obj_set_width( ui_btnPack1, lv_pct(90));
lv_obj_set_height( ui_btnPack1, lv_pct(10));
lv_obj_set_x( ui_btnPack1, 0 );
lv_obj_set_y( ui_btnPack1, -1 );
lv_obj_set_align( ui_btnPack1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnPack1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_btnPack1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_btnPack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPack1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPack1, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPack1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPack1 = lv_label_create(ui_btnPack1);
lv_obj_set_width( ui_lblPack1, lv_pct(100));
lv_obj_set_height( ui_lblPack1, lv_pct(100));
lv_obj_set_align( ui_lblPack1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPack1,"#1     52.5V");
lv_obj_set_style_text_align(ui_lblPack1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPack2 = lv_btn_create(ui_MainRightPanel);
lv_obj_set_width( ui_btnPack2, lv_pct(90));
lv_obj_set_height( ui_btnPack2, lv_pct(10));
lv_obj_set_x( ui_btnPack2, 0 );
lv_obj_set_y( ui_btnPack2, -1 );
lv_obj_set_align( ui_btnPack2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnPack2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_btnPack2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_btnPack2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPack2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPack2, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPack2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPack2 = lv_label_create(ui_btnPack2);
lv_obj_set_width( ui_lblPack2, lv_pct(100));
lv_obj_set_height( ui_lblPack2, lv_pct(100));
lv_obj_set_align( ui_lblPack2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPack2,"#1     52.5V");
lv_obj_set_style_text_align(ui_lblPack2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPack3 = lv_btn_create(ui_MainRightPanel);
lv_obj_set_width( ui_btnPack3, lv_pct(90));
lv_obj_set_height( ui_btnPack3, lv_pct(10));
lv_obj_set_x( ui_btnPack3, 0 );
lv_obj_set_y( ui_btnPack3, -1 );
lv_obj_set_align( ui_btnPack3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnPack3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_btnPack3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_btnPack3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPack3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPack3, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPack3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPack3 = lv_label_create(ui_btnPack3);
lv_obj_set_width( ui_lblPack3, lv_pct(100));
lv_obj_set_height( ui_lblPack3, lv_pct(100));
lv_obj_set_align( ui_lblPack3, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPack3,"#1     52.5V");
lv_obj_set_style_text_align(ui_lblPack3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPack4 = lv_btn_create(ui_MainRightPanel);
lv_obj_set_width( ui_btnPack4, lv_pct(90));
lv_obj_set_height( ui_btnPack4, lv_pct(10));
lv_obj_set_x( ui_btnPack4, 0 );
lv_obj_set_y( ui_btnPack4, -1 );
lv_obj_set_align( ui_btnPack4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnPack4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_btnPack4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_btnPack4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPack4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPack4, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPack4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPack4 = lv_label_create(ui_btnPack4);
lv_obj_set_width( ui_lblPack4, lv_pct(100));
lv_obj_set_height( ui_lblPack4, lv_pct(100));
lv_obj_set_align( ui_lblPack4, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPack4,"#1     52.5V");
lv_obj_set_style_text_align(ui_lblPack4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPack5 = lv_btn_create(ui_MainRightPanel);
lv_obj_set_width( ui_btnPack5, lv_pct(90));
lv_obj_set_height( ui_btnPack5, lv_pct(10));
lv_obj_set_x( ui_btnPack5, 0 );
lv_obj_set_y( ui_btnPack5, -1 );
lv_obj_set_align( ui_btnPack5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnPack5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_btnPack5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_btnPack5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPack5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPack5, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPack5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPack5 = lv_label_create(ui_btnPack5);
lv_obj_set_width( ui_lblPack5, lv_pct(100));
lv_obj_set_height( ui_lblPack5, lv_pct(100));
lv_obj_set_align( ui_lblPack5, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPack5,"#1     52.5V");
lv_obj_set_style_text_align(ui_lblPack5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPack6 = lv_btn_create(ui_MainRightPanel);
lv_obj_set_width( ui_btnPack6, lv_pct(90));
lv_obj_set_height( ui_btnPack6, lv_pct(10));
lv_obj_set_x( ui_btnPack6, 0 );
lv_obj_set_y( ui_btnPack6, -1 );
lv_obj_set_align( ui_btnPack6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnPack6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_btnPack6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_btnPack6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPack6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPack6, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPack6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPack6 = lv_label_create(ui_btnPack6);
lv_obj_set_width( ui_lblPack6, lv_pct(100));
lv_obj_set_height( ui_lblPack6, lv_pct(100));
lv_obj_set_align( ui_lblPack6, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPack6,"#1     52.5V");
lv_obj_set_style_text_align(ui_lblPack6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPack7 = lv_btn_create(ui_MainRightPanel);
lv_obj_set_width( ui_btnPack7, lv_pct(90));
lv_obj_set_height( ui_btnPack7, lv_pct(10));
lv_obj_set_x( ui_btnPack7, 0 );
lv_obj_set_y( ui_btnPack7, -1 );
lv_obj_set_align( ui_btnPack7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnPack7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_btnPack7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_btnPack7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPack7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPack7, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPack7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPack7 = lv_label_create(ui_btnPack7);
lv_obj_set_width( ui_lblPack7, lv_pct(100));
lv_obj_set_height( ui_lblPack7, lv_pct(100));
lv_obj_set_align( ui_lblPack7, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPack7,"#1     52.5V");
lv_obj_set_style_text_align(ui_lblPack7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnPack8 = lv_btn_create(ui_MainRightPanel);
lv_obj_set_width( ui_btnPack8, lv_pct(90));
lv_obj_set_height( ui_btnPack8, lv_pct(10));
lv_obj_set_x( ui_btnPack8, 0 );
lv_obj_set_y( ui_btnPack8, -1 );
lv_obj_set_align( ui_btnPack8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_btnPack8,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_btnPack8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_btnPack8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPack8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_btnPack8, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_btnPack8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPack8 = lv_label_create(ui_btnPack8);
lv_obj_set_width( ui_lblPack8, lv_pct(100));
lv_obj_set_height( ui_lblPack8, lv_pct(100));
lv_obj_set_align( ui_lblPack8, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPack8,"#1     52.5V");
lv_obj_set_style_text_align(ui_lblPack8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPack1, ui_event_btnPack1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPack2, ui_event_btnPack2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPack3, ui_event_btnPack3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPack4, ui_event_btnPack4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPack5, ui_event_btnPack5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPack6, ui_event_btnPack6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPack7, ui_event_btnPack7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPack8, ui_event_btnPack8, LV_EVENT_ALL, NULL);

}
