// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.3
// Project name: LithumeBms

#include "../ui.h"

void ui_SettingScreen_screen_init(void)
{
ui_SettingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingScreen, lv_color_hex(0x4C4B55), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetHeader = lv_obj_create(ui_SettingScreen);
lv_obj_set_width( ui_SetHeader, lv_pct(100));
lv_obj_set_height( ui_SetHeader, lv_pct(10));
lv_obj_set_align( ui_SetHeader, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_SetHeader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SetHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SetHeader, lv_color_hex(0x2F2C2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SetHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SetHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SetHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SetHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_SetHeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_SetHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_SetHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_SetHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateLabel1 = lv_label_create(ui_SetHeader);
lv_obj_set_width( ui_DateLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DateLabel1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_DateLabel1,"2023-11-03");
lv_obj_set_style_text_color(ui_DateLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DateLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeLabel1 = lv_label_create(ui_SetHeader);
lv_obj_set_width( ui_TimeLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TimeLabel1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_TimeLabel1,"PM 8:35");
lv_obj_set_style_text_color(ui_TimeLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaderTitle1 = lv_label_create(ui_SetHeader);
lv_obj_set_width( ui_HeaderTitle1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeaderTitle1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HeaderTitle1, LV_ALIGN_CENTER );
lv_label_set_text(ui_HeaderTitle1,"BMS SETTING");
lv_obj_set_style_text_color(ui_HeaderTitle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeaderTitle1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeaderTitle1, &ui_font_arial28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetLeftPannel = lv_obj_create(ui_SettingScreen);
lv_obj_set_width( ui_SetLeftPannel, lv_pct(20));
lv_obj_set_height( ui_SetLeftPannel, lv_pct(80));
lv_obj_set_x( ui_SetLeftPannel, 1 );
lv_obj_set_y( ui_SetLeftPannel, 0 );
lv_obj_set_align( ui_SetLeftPannel, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_SetLeftPannel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_SetLeftPannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SetLeftPannel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SetLeftPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SetLeftPannel, lv_color_hex(0x353030), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SetLeftPannel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SetLeftPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TotalVoltage1 = lv_label_create(ui_SetLeftPannel);
lv_obj_set_height( ui_TotalVoltage1, lv_pct(80));
lv_obj_set_width( ui_TotalVoltage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_TotalVoltage1, 2 );
lv_obj_set_y( ui_TotalVoltage1, 9 );
lv_label_set_text(ui_TotalVoltage1,"SYSTEM SET");
lv_obj_set_style_text_color(ui_TotalVoltage1, lv_color_hex(0x1401F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TotalVoltage1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_SetLeftPannel);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 30);
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"메 인");
lv_obj_set_style_text_font(ui_Label2, &ui_font_malgunFont1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SaveSettingButton = lv_btn_create(ui_SetLeftPannel);
lv_obj_set_width( ui_SaveSettingButton, 100);
lv_obj_set_height( ui_SaveSettingButton, 30);
lv_obj_set_x( ui_SaveSettingButton, -1 );
lv_obj_set_y( ui_SaveSettingButton, -39 );
lv_obj_set_align( ui_SaveSettingButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SaveSettingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SaveSettingButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SaveSettingButton, lv_color_hex(0x332222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SaveSettingButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_SaveSettingButton);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"저 장");
lv_obj_set_style_text_font(ui_Label8, &ui_font_malgunFont1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetRightPannel = lv_obj_create(ui_SettingScreen);
lv_obj_set_width( ui_SetRightPannel, lv_pct(80));
lv_obj_set_height( ui_SetRightPannel, lv_pct(80));
lv_obj_set_align( ui_SetRightPannel, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_SetRightPannel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SetRightPannel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SetRightPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SetRightPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SetRightPannel, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SetRightPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SetRightPannel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SetRightPannel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_SetRightPannel);
lv_obj_set_width( ui_Panel1, 307);
lv_obj_set_height( ui_Panel1, 38);
lv_obj_set_x( ui_Panel1, -167 );
lv_obj_set_y( ui_Panel1, -160 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblIPADDRESS = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_lblIPADDRESS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblIPADDRESS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblIPADDRESS, -111 );
lv_obj_set_y( ui_lblIPADDRESS, 0 );
lv_obj_set_align( ui_lblIPADDRESS, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblIPADDRESS,"IPADDRESS");
lv_obj_set_style_text_color(ui_lblIPADDRESS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblIPADDRESS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtIPADDRESS1 = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_txtIPADDRESS1, 48);
lv_obj_set_height( ui_txtIPADDRESS1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtIPADDRESS1, -30 );
lv_obj_set_y( ui_txtIPADDRESS1, 0 );
lv_obj_set_align( ui_txtIPADDRESS1, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtIPADDRESS1,3);
lv_textarea_set_text(ui_txtIPADDRESS1,"192");
lv_textarea_set_placeholder_text(ui_txtIPADDRESS1,"Placeholder...");
lv_textarea_set_one_line(ui_txtIPADDRESS1,true);



ui_txtIPADDRESS2 = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_txtIPADDRESS2, 48);
lv_obj_set_height( ui_txtIPADDRESS2, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtIPADDRESS2, 21 );
lv_obj_set_y( ui_txtIPADDRESS2, 0 );
lv_obj_set_align( ui_txtIPADDRESS2, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtIPADDRESS2,3);
lv_textarea_set_text(ui_txtIPADDRESS2,"168");
lv_textarea_set_placeholder_text(ui_txtIPADDRESS2,"Placeholder...");
lv_textarea_set_one_line(ui_txtIPADDRESS2,true);



ui_txtIPADDRESS3 = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_txtIPADDRESS3, 48);
lv_obj_set_height( ui_txtIPADDRESS3, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtIPADDRESS3, 72 );
lv_obj_set_y( ui_txtIPADDRESS3, 0 );
lv_obj_set_align( ui_txtIPADDRESS3, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtIPADDRESS3,3);
lv_textarea_set_text(ui_txtIPADDRESS3,"10");
lv_textarea_set_placeholder_text(ui_txtIPADDRESS3,"Placeholder...");
lv_textarea_set_one_line(ui_txtIPADDRESS3,true);



ui_txtIPADDRESS4 = lv_textarea_create(ui_Panel1);
lv_obj_set_width( ui_txtIPADDRESS4, 48);
lv_obj_set_height( ui_txtIPADDRESS4, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtIPADDRESS4, 122 );
lv_obj_set_y( ui_txtIPADDRESS4, 0 );
lv_obj_set_align( ui_txtIPADDRESS4, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtIPADDRESS4,3);
lv_textarea_set_text(ui_txtIPADDRESS4,"10");
lv_textarea_set_placeholder_text(ui_txtIPADDRESS4,"Placeholder...");
lv_textarea_set_one_line(ui_txtIPADDRESS4,true);



ui_Panel2 = lv_obj_create(ui_SetRightPannel);
lv_obj_set_width( ui_Panel2, 307);
lv_obj_set_height( ui_Panel2, 38);
lv_obj_set_x( ui_Panel2, -167 );
lv_obj_set_y( ui_Panel2, -110 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblIPADDRESS1 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_lblIPADDRESS1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblIPADDRESS1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblIPADDRESS1, -111 );
lv_obj_set_y( ui_lblIPADDRESS1, 0 );
lv_obj_set_align( ui_lblIPADDRESS1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblIPADDRESS1,"SUBNET");
lv_obj_set_style_text_color(ui_lblIPADDRESS1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblIPADDRESS1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtSUBNET1 = lv_textarea_create(ui_Panel2);
lv_obj_set_width( ui_txtSUBNET1, 48);
lv_obj_set_height( ui_txtSUBNET1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtSUBNET1, -30 );
lv_obj_set_y( ui_txtSUBNET1, 0 );
lv_obj_set_align( ui_txtSUBNET1, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtSUBNET1,3);
lv_textarea_set_text(ui_txtSUBNET1,"255");
lv_textarea_set_placeholder_text(ui_txtSUBNET1,"Placeholder...");
lv_textarea_set_one_line(ui_txtSUBNET1,true);



ui_txtSUBNET2 = lv_textarea_create(ui_Panel2);
lv_obj_set_width( ui_txtSUBNET2, 48);
lv_obj_set_height( ui_txtSUBNET2, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtSUBNET2, 21 );
lv_obj_set_y( ui_txtSUBNET2, 0 );
lv_obj_set_align( ui_txtSUBNET2, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtSUBNET2,3);
lv_textarea_set_text(ui_txtSUBNET2,"255");
lv_textarea_set_placeholder_text(ui_txtSUBNET2,"Placeholder...");
lv_textarea_set_one_line(ui_txtSUBNET2,true);



ui_txtSUBNET3 = lv_textarea_create(ui_Panel2);
lv_obj_set_width( ui_txtSUBNET3, 48);
lv_obj_set_height( ui_txtSUBNET3, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtSUBNET3, 72 );
lv_obj_set_y( ui_txtSUBNET3, 0 );
lv_obj_set_align( ui_txtSUBNET3, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtSUBNET3,3);
lv_textarea_set_text(ui_txtSUBNET3,"255");
lv_textarea_set_placeholder_text(ui_txtSUBNET3,"Placeholder...");
lv_textarea_set_one_line(ui_txtSUBNET3,true);



ui_txtSUBNET4 = lv_textarea_create(ui_Panel2);
lv_obj_set_width( ui_txtSUBNET4, 48);
lv_obj_set_height( ui_txtSUBNET4, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtSUBNET4, 122 );
lv_obj_set_y( ui_txtSUBNET4, 0 );
lv_obj_set_align( ui_txtSUBNET4, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtSUBNET4,3);
lv_textarea_set_text(ui_txtSUBNET4,"0");
lv_textarea_set_placeholder_text(ui_txtSUBNET4,"Placeholder...");
lv_textarea_set_one_line(ui_txtSUBNET4,true);



ui_Panel3 = lv_obj_create(ui_SetRightPannel);
lv_obj_set_width( ui_Panel3, 307);
lv_obj_set_height( ui_Panel3, 38);
lv_obj_set_x( ui_Panel3, -167 );
lv_obj_set_y( ui_Panel3, -60 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblIPADDRESS2 = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_lblIPADDRESS2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblIPADDRESS2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblIPADDRESS2, -111 );
lv_obj_set_y( ui_lblIPADDRESS2, 0 );
lv_obj_set_align( ui_lblIPADDRESS2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblIPADDRESS2,"GATEWAY");
lv_obj_set_style_text_color(ui_lblIPADDRESS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblIPADDRESS2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtGATEWAY1 = lv_textarea_create(ui_Panel3);
lv_obj_set_width( ui_txtGATEWAY1, 48);
lv_obj_set_height( ui_txtGATEWAY1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtGATEWAY1, -30 );
lv_obj_set_y( ui_txtGATEWAY1, 0 );
lv_obj_set_align( ui_txtGATEWAY1, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtGATEWAY1,3);
lv_textarea_set_text(ui_txtGATEWAY1,"192");
lv_textarea_set_placeholder_text(ui_txtGATEWAY1,"Placeholder...");
lv_textarea_set_one_line(ui_txtGATEWAY1,true);



ui_txtGATEWAY2 = lv_textarea_create(ui_Panel3);
lv_obj_set_width( ui_txtGATEWAY2, 48);
lv_obj_set_height( ui_txtGATEWAY2, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtGATEWAY2, 21 );
lv_obj_set_y( ui_txtGATEWAY2, 0 );
lv_obj_set_align( ui_txtGATEWAY2, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtGATEWAY2,3);
lv_textarea_set_text(ui_txtGATEWAY2,"168");
lv_textarea_set_placeholder_text(ui_txtGATEWAY2,"Placeholder...");
lv_textarea_set_one_line(ui_txtGATEWAY2,true);



ui_txtGATEWAY3 = lv_textarea_create(ui_Panel3);
lv_obj_set_width( ui_txtGATEWAY3, 48);
lv_obj_set_height( ui_txtGATEWAY3, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtGATEWAY3, 72 );
lv_obj_set_y( ui_txtGATEWAY3, 0 );
lv_obj_set_align( ui_txtGATEWAY3, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtGATEWAY3,3);
lv_textarea_set_text(ui_txtGATEWAY3,"10");
lv_textarea_set_placeholder_text(ui_txtGATEWAY3,"Placeholder...");
lv_textarea_set_one_line(ui_txtGATEWAY3,true);



ui_txtGATEWAY4 = lv_textarea_create(ui_Panel3);
lv_obj_set_width( ui_txtGATEWAY4, 48);
lv_obj_set_height( ui_txtGATEWAY4, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtGATEWAY4, 122 );
lv_obj_set_y( ui_txtGATEWAY4, 0 );
lv_obj_set_align( ui_txtGATEWAY4, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtGATEWAY4,3);
lv_textarea_set_text(ui_txtGATEWAY4,"1");
lv_textarea_set_placeholder_text(ui_txtGATEWAY4,"Placeholder...");
lv_textarea_set_one_line(ui_txtGATEWAY4,true);



ui_Panel4 = lv_obj_create(ui_SetRightPannel);
lv_obj_set_width( ui_Panel4, 307);
lv_obj_set_height( ui_Panel4, 38);
lv_obj_set_x( ui_Panel4, -167 );
lv_obj_set_y( ui_Panel4, -10 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblIPADDRESS3 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_lblIPADDRESS3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblIPADDRESS3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblIPADDRESS3, -107 );
lv_obj_set_y( ui_lblIPADDRESS3, 0 );
lv_obj_set_align( ui_lblIPADDRESS3, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblIPADDRESS3,"Device Name");
lv_obj_set_style_text_color(ui_lblIPADDRESS3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblIPADDRESS3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtDEVICENAME = lv_textarea_create(ui_Panel4);
lv_obj_set_width( ui_txtDEVICENAME, 205);
lv_obj_set_height( ui_txtDEVICENAME, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtDEVICENAME, 51 );
lv_obj_set_y( ui_txtDEVICENAME, 0 );
lv_obj_set_align( ui_txtDEVICENAME, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtDEVICENAME,20);
lv_textarea_set_text(ui_txtDEVICENAME,"BMS RACK 1");
lv_textarea_set_placeholder_text(ui_txtDEVICENAME,"Placeholder...");
lv_textarea_set_one_line(ui_txtDEVICENAME,true);



ui_Panel5 = lv_obj_create(ui_SetRightPannel);
lv_obj_set_width( ui_Panel5, 307);
lv_obj_set_height( ui_Panel5, 110);
lv_obj_set_x( ui_Panel5, -168 );
lv_obj_set_y( ui_Panel5, 89 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTime = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_lblTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTime, -111 );
lv_obj_set_y( ui_lblTime, 0 );
lv_obj_set_align( ui_lblTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTime,"Date TIme");
lv_obj_set_style_text_color(ui_lblTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtYear = lv_textarea_create(ui_Panel5);
lv_obj_set_width( ui_txtYear, 48);
lv_obj_set_height( ui_txtYear, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtYear, -30 );
lv_obj_set_y( ui_txtYear, -15 );
lv_obj_set_align( ui_txtYear, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtYear,3);
lv_textarea_set_text(ui_txtYear,"192");
lv_textarea_set_placeholder_text(ui_txtYear,"Placeholder...");
lv_textarea_set_one_line(ui_txtYear,true);



ui_txtMonth = lv_textarea_create(ui_Panel5);
lv_obj_set_width( ui_txtMonth, 48);
lv_obj_set_height( ui_txtMonth, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtMonth, 27 );
lv_obj_set_y( ui_txtMonth, -15 );
lv_obj_set_align( ui_txtMonth, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtMonth,3);
lv_textarea_set_text(ui_txtMonth,"168");
lv_textarea_set_placeholder_text(ui_txtMonth,"Placeholder...");
lv_textarea_set_one_line(ui_txtMonth,true);



ui_txtDay = lv_textarea_create(ui_Panel5);
lv_obj_set_width( ui_txtDay, 48);
lv_obj_set_height( ui_txtDay, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtDay, 83 );
lv_obj_set_y( ui_txtDay, -15 );
lv_obj_set_align( ui_txtDay, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtDay,3);
lv_textarea_set_text(ui_txtDay,"10");
lv_textarea_set_placeholder_text(ui_txtDay,"Placeholder...");
lv_textarea_set_one_line(ui_txtDay,true);



ui_txtTime = lv_textarea_create(ui_Panel5);
lv_obj_set_width( ui_txtTime, 48);
lv_obj_set_height( ui_txtTime, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtTime, -30 );
lv_obj_set_y( ui_txtTime, 32 );
lv_obj_set_align( ui_txtTime, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtTime,3);
lv_textarea_set_text(ui_txtTime,"1");
lv_textarea_set_placeholder_text(ui_txtTime,"Placeholder...");
lv_textarea_set_one_line(ui_txtTime,true);



ui_txtMinute = lv_textarea_create(ui_Panel5);
lv_obj_set_width( ui_txtMinute, 48);
lv_obj_set_height( ui_txtMinute, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtMinute, 25 );
lv_obj_set_y( ui_txtMinute, 33 );
lv_obj_set_align( ui_txtMinute, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtMinute,3);
lv_textarea_set_text(ui_txtMinute,"1");
lv_textarea_set_placeholder_text(ui_txtMinute,"Placeholder...");
lv_textarea_set_one_line(ui_txtMinute,true);



ui_txtSecond = lv_textarea_create(ui_Panel5);
lv_obj_set_width( ui_txtSecond, 48);
lv_obj_set_height( ui_txtSecond, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_txtSecond, 82 );
lv_obj_set_y( ui_txtSecond, 33 );
lv_obj_set_align( ui_txtSecond, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_txtSecond,3);
lv_textarea_set_text(ui_txtSecond,"1");
lv_textarea_set_placeholder_text(ui_txtSecond,"Placeholder...");
lv_textarea_set_one_line(ui_txtSecond,true);



ui_SetBottomPannel = lv_obj_create(ui_SettingScreen);
lv_obj_set_width( ui_SetBottomPannel, lv_pct(100));
lv_obj_set_height( ui_SetBottomPannel, lv_pct(10));
lv_obj_set_align( ui_SetBottomPannel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_SetBottomPannel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SetBottomPannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SetBottomPannel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SetBottomPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SetBottomPannel, lv_color_hex(0x2F2C2C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SetBottomPannel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SetBottomPannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CompanyLabel2 = lv_label_create(ui_SetBottomPannel);
lv_obj_set_width( ui_CompanyLabel2, 120);
lv_obj_set_height( ui_CompanyLabel2, 15);
lv_obj_set_align( ui_CompanyLabel2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_CompanyLabel2,"IFTECH Co.,LTD");
lv_obj_set_style_text_color(ui_CompanyLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CompanyLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CompanyLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CompanyLabel3 = lv_label_create(ui_SetBottomPannel);
lv_obj_set_width( ui_CompanyLabel3, lv_pct(70));
lv_obj_set_height( ui_CompanyLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CompanyLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_CompanyLabel3,"STATUS : NORMAL");
lv_obj_set_style_text_color(ui_CompanyLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CompanyLabel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_CompanyLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VersionLabel1 = lv_label_create(ui_SetBottomPannel);
lv_obj_set_width( ui_VersionLabel1, lv_pct(15));
lv_obj_set_height( ui_VersionLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VersionLabel1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_VersionLabel1,"V1.0.1");
lv_obj_set_style_text_color(ui_VersionLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_VersionLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_VersionLabel1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Keyboard1 = lv_keyboard_create(ui_SettingScreen);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_TEXT_UPPER);
lv_obj_set_width( ui_Keyboard1, 544);
lv_obj_set_height( ui_Keyboard1, 163);
lv_obj_set_x( ui_Keyboard1, 41 );
lv_obj_set_y( ui_Keyboard1, 99 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SaveSettingButton, ui_event_SaveSettingButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtIPADDRESS1, ui_event_txtIPADDRESS1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtIPADDRESS2, ui_event_txtIPADDRESS2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtIPADDRESS3, ui_event_txtIPADDRESS3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtIPADDRESS4, ui_event_txtIPADDRESS4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtSUBNET1, ui_event_txtSUBNET1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtSUBNET2, ui_event_txtSUBNET2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtSUBNET3, ui_event_txtSUBNET3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtSUBNET4, ui_event_txtSUBNET4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtGATEWAY1, ui_event_txtGATEWAY1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtGATEWAY2, ui_event_txtGATEWAY2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtGATEWAY3, ui_event_txtGATEWAY3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtGATEWAY4, ui_event_txtGATEWAY4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtDEVICENAME, ui_event_txtDEVICENAME, LV_EVENT_ALL, NULL);

}
